name: little_emmi
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using flutter pub publish. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running flutter pub upgrade --major-versions. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run flutter pub outdated.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  webview_flutter: ^4.13.1
  flutter_tts: ^3.8.3
  image_picker: ^1.1.2
  flutter_blue_plus: ^1.34.5
  flutter_libserialport: ^0.6.0  # Fixes SerialPort errors
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  model_viewer_plus: ^1.7.0
  provider: ^6.1.5+1
  connectivity_plus: ^6.1.0
  uuid: ^4.5.2
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0 # Add this line
  device_info_plus: ^10.1.0
  tflite_flutter: ^0.12.1
  image: ^4.1.7
  font_awesome_flutter: ^10.10.0
  percent_indicator: ^4.2.5
  intl: ^0.18.0
  url_launcher: ^6.3.2
  archive: ^3.6.1
  flutter_inappwebview: ^6.1.5
  sensors_plus: ^7.0.0
  shared_preferences: ^2.2.3
  dotted_border: ^2.0.0
  process_run: 1.2.4
  path: ^1.9.0
  flutter_code_editor: ^0.3.1 # Check pub.dev for the latest version
  flutter_highlight: ^0.7.0  # Required by the code editor for syntax highlighting
  path_provider: ^2.1.3
  audioplayers: ^6.0.0
  # Required for handling camera/location permissions
  permission_handler: ^12.0.1
  # Math library for 3D vector calculations
  vector_math: ^2.1.4
  http: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  webview_windows: ^0.4.0
  google_generative_ai: ^0.4.7
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  camera_windows: ^0.2.1
  camera: ^0.10.5+9

  highlight: any
  camera_macos: ^0.0.9
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  pointer_interceptor: ^0.10.1+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/qubiq_logo.png"
  min_sdk_android: 21

  # ✅ ENABLE MACOS SUPPORT
  macos:
    generate: true
    image_path: "assets/images/qubiq_logo.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - ./lib/Resources/little_emmi.svg
    - ./lib/Resources/BlocksStructure/blueCmd.svg
    - ./lib/Resources/MovementIcons/Foward.svg
    - ./lib/Resources/MovementIcons/Back.svg
    - ./lib/Resources/MovementIcons/Up.svg
    - ./lib/Resources/MovementIcons/Down.svg
    - lib/Resources/loopIcons/repeat.png
    - lib/Resources/loopIcons/repeatblock.png
    - ./lib/Resources/loopIcons/Repeat.svg
    - ./lib/Resources/loopIcons/repeatsvg.svg
    - assets/images/qubiq_logo.png
    - assets/pythonide/
    - assets/emmi_html/
    - assets/emmi_html/css/
    - assets/emmi_html/js/
    - assets/emmi_html/js/generators/
    - assets/emmi_html/js/commands/
    - assets/emmi_html/js/tests/
    - assets/emmi_html/blocks/
    - assets/emmi_html/media/
    - assets/emmi_html/headers/
    - assets/emmi_html/lib/blockly/
    - assets/emmi_html/lib/blockly/media/
    - assets/emmi_html/lib/prism/
    - assets/emmi_html/lib/prism/themes/
    - assets/emmi_html/lib/prism/components/
    - assets/emmi_html/lib/font-awesome/css/
    - assets/emmi_html/lib/font-awesome/webfonts/
    - assets/curriculum.json
    - assets/mobilenet_feature.tflite
    - assets/images/chatai.png
    - assets/images/
    - "assets/excel_web_ai/dist/"
    - "assets/excel_web_ai/dist/assets/"
    - assets/antipython_web/
    - assets/antipython_web/lib/
    - assets/antipython_web/lib/skulpt/
    - assets/antipython_web/lib/monaco/
    - assets/antipython_web/lib/monaco/vs/
    - assets/antipython_web/lib/monaco/vs/basic-languages/
    - assets/antipython_web/lib/monaco/vs/basic-languages/postiats/
    - assets/antipython_web/lib/monaco/vs/basic-languages/scheme/
    - assets/antipython_web/lib/monaco/vs/basic-languages/sb/
    - assets/antipython_web/lib/monaco/vs/basic-languages/mdx/
    - assets/antipython_web/lib/monaco/vs/basic-languages/pascal/
    - assets/antipython_web/lib/monaco/vs/basic-languages/cameligo/
    - assets/antipython_web/lib/monaco/vs/basic-languages/razor/
    - assets/antipython_web/lib/monaco/vs/basic-languages/powerquery/
    - assets/antipython_web/lib/monaco/vs/basic-languages/apex/
    - assets/antipython_web/lib/monaco/vs/basic-languages/go/
    - assets/antipython_web/lib/monaco/vs/basic-languages/systemverilog/
    - assets/antipython_web/lib/monaco/vs/basic-languages/sparql/
    - assets/antipython_web/lib/monaco/vs/basic-languages/azcli/
    - assets/antipython_web/lib/monaco/vs/basic-languages/python/
    - assets/antipython_web/lib/monaco/vs/basic-languages/css/
    - assets/antipython_web/lib/monaco/vs/basic-languages/clojure/
    - assets/antipython_web/lib/monaco/vs/basic-languages/less/
    - assets/antipython_web/lib/monaco/vs/basic-languages/elixir/
    - assets/antipython_web/lib/monaco/vs/basic-languages/redis/
    - assets/antipython_web/lib/monaco/vs/basic-languages/lexon/
    - assets/antipython_web/lib/monaco/vs/basic-languages/dockerfile/
    - assets/antipython_web/lib/monaco/vs/basic-languages/dart/
    - assets/antipython_web/lib/monaco/vs/basic-languages/shell/
    - assets/antipython_web/lib/monaco/vs/basic-languages/markdown/
    - assets/antipython_web/lib/monaco/vs/basic-languages/scss/
    - assets/antipython_web/lib/monaco/vs/basic-languages/sophia/
    - assets/antipython_web/lib/monaco/vs/basic-languages/perl/
    - assets/antipython_web/lib/monaco/vs/basic-languages/typescript/
    - assets/antipython_web/lib/monaco/vs/basic-languages/rust/
    - assets/antipython_web/lib/monaco/vs/basic-languages/pug/
    - assets/antipython_web/lib/monaco/vs/basic-languages/fsharp/
    - assets/antipython_web/lib/monaco/vs/basic-languages/r/
    - assets/antipython_web/lib/monaco/vs/basic-languages/freemarker2/
    - assets/antipython_web/lib/monaco/vs/basic-languages/liquid/
    - assets/antipython_web/lib/monaco/vs/basic-languages/java/
    - assets/antipython_web/lib/monaco/vs/basic-languages/html/
    - assets/antipython_web/lib/monaco/vs/basic-languages/abap/
    - assets/antipython_web/lib/monaco/vs/basic-languages/kotlin/
    - assets/antipython_web/lib/monaco/vs/basic-languages/cypher/
    - assets/antipython_web/lib/monaco/vs/basic-languages/php/
    - assets/antipython_web/lib/monaco/vs/basic-languages/lua/
    - assets/antipython_web/lib/monaco/vs/basic-languages/xml/
    - assets/antipython_web/lib/monaco/vs/basic-languages/pascaligo/
    - assets/antipython_web/lib/monaco/vs/basic-languages/solidity/
    - assets/antipython_web/lib/monaco/vs/basic-languages/st/
    - assets/antipython_web/lib/monaco/vs/basic-languages/redshift/
    - assets/antipython_web/lib/monaco/vs/basic-languages/vb/
    - assets/antipython_web/lib/monaco/vs/basic-languages/powershell/
    - assets/antipython_web/lib/monaco/vs/basic-languages/mips/
    - assets/antipython_web/lib/monaco/vs/basic-languages/pla/
    - assets/antipython_web/lib/monaco/vs/basic-languages/tcl/
    - assets/antipython_web/lib/monaco/vs/basic-languages/ini/
    - assets/antipython_web/lib/monaco/vs/basic-languages/handlebars/
    - assets/antipython_web/lib/monaco/vs/basic-languages/scala/
    - assets/antipython_web/lib/monaco/vs/basic-languages/hcl/
    - assets/antipython_web/lib/monaco/vs/basic-languages/cpp/
    - assets/antipython_web/lib/monaco/vs/basic-languages/swift/
    - assets/antipython_web/lib/monaco/vs/basic-languages/graphql/
    - assets/antipython_web/lib/monaco/vs/basic-languages/qsharp/
    - assets/antipython_web/lib/monaco/vs/basic-languages/mysql/
    - assets/antipython_web/lib/monaco/vs/basic-languages/coffee/
    - assets/antipython_web/lib/monaco/vs/basic-languages/csp/
    - assets/antipython_web/lib/monaco/vs/basic-languages/pgsql/
    - assets/antipython_web/lib/monaco/vs/basic-languages/m3/
    - assets/antipython_web/lib/monaco/vs/basic-languages/yaml/
    - assets/antipython_web/lib/monaco/vs/basic-languages/csharp/
    - assets/antipython_web/lib/monaco/vs/basic-languages/julia/
    - assets/antipython_web/lib/monaco/vs/basic-languages/bat/
    - assets/antipython_web/lib/monaco/vs/basic-languages/javascript/
    - assets/antipython_web/lib/monaco/vs/basic-languages/bicep/
    - assets/antipython_web/lib/monaco/vs/basic-languages/twig/
    - assets/antipython_web/lib/monaco/vs/basic-languages/msdax/
    - assets/antipython_web/lib/monaco/vs/basic-languages/wgsl/
    - assets/antipython_web/lib/monaco/vs/basic-languages/restructuredtext/
    - assets/antipython_web/lib/monaco/vs/basic-languages/objective-c/
    - assets/antipython_web/lib/monaco/vs/basic-languages/protobuf/
    - assets/antipython_web/lib/monaco/vs/basic-languages/ecl/
    - assets/antipython_web/lib/monaco/vs/basic-languages/ruby/
    - assets/antipython_web/lib/monaco/vs/basic-languages/flow9/
    - assets/antipython_web/lib/monaco/vs/basic-languages/sql/
    - assets/antipython_web/lib/monaco/vs/language/
    - assets/antipython_web/lib/monaco/vs/language/css/
    - assets/antipython_web/lib/monaco/vs/language/typescript/
    - assets/antipython_web/lib/monaco/vs/language/html/
    - assets/antipython_web/lib/monaco/vs/language/json/
    - assets/antipython_web/lib/monaco/vs/base/
    - assets/antipython_web/lib/monaco/vs/base/browser/
    - assets/antipython_web/lib/monaco/vs/base/browser/ui/
    - assets/antipython_web/lib/monaco/vs/base/browser/ui/codicons/
    - assets/antipython_web/lib/monaco/vs/base/browser/ui/codicons/codicon/
    - assets/antipython_web/lib/monaco/vs/base/common/
    - assets/antipython_web/lib/monaco/vs/base/common/worker/
    - assets/antipython_web/lib/monaco/vs/base/worker/
    - assets/antipython_web/lib/monaco/vs/editor/
    - assets/antipython_web/lib/lucide/
    - assets/antipython_web/lib/fonts/
    - assets/antipython_web/assets/
    - assets/qubiq_web/
    - assets/qubiq_web/assets/
    - assets/www/
    - assets/www/blocks/
    - assets/www/lib/
    - assets/www/lib/codemirror/
    - assets/www/lib/skulpt/
    - assets/www/lib/blockly/
    - assets/www/index_MIT.html
    - assets/www/vite.svg
    - assets/www/assets/index-JKwT_vHL.css
    - assets/www/assets/index-xPsAilHw.js
    - assets/excel_web/dist/
    - assets/excel_web/dist/assets/
    - assets/excel_web/dist/index.html
    - assets/excel_web/dist/vite.svg
    - assets/excel_web/dist/assets/
    - assets/word_web/word/
    - assets/web/dist/
    - assets/web/dist/assets/
    - assets/powerpoint_no_ai/
    - assets/teachable/image/
    - assets/teachable/image/assets/
    - assets/teachable/audio/
    - assets/teachable/audio/assets/
    - assets/teachable/pose/
    - assets/teachable/pose/assets/
    - assets/html_learning/
    - assets/paint/
    - assets/keyboard_game/
    - assets/powerpoint_app/
    - assets/drone_block_coding/
    - assets/drone_block_coding/assets/
    - assets/drone_block_coding/media/
    - assets/emmi_lite/
    - assets/emmi_lite/blocks/
    - assets/emmi_lite/css/
    - assets/emmi_lite/headers/
    - assets/emmi_lite/js/
    - assets/emmi_lite/lib/
    - assets/emmi_lite/media/
    - assets/assets/emmi-bot-lite/
    - assets/assets/emmi-bot-lite/blocks/
    - assets/assets/emmi-bot-lite/css/
    - assets/assets/emmi-bot-lite/headers/
    - assets/assets/emmi-bot-lite/js/
    - assets/assets/emmi-bot-lite/js/commands/
    - assets/assets/emmi-bot-lite/js/generators/
    - assets/assets/emmi-bot-lite/js/tests/
    - assets/assets/emmi-bot-lite/lib/
    - assets/assets/emmi-bot-lite/lib/blockly/
    - assets/assets/emmi-bot-lite/lib/blockly/media/
    - assets/assets/emmi-bot-lite/lib/font-awesome/
    - assets/assets/emmi-bot-lite/lib/font-awesome/css/
    - assets/assets/emmi-bot-lite/lib/font-awesome/webfonts/
    - assets/assets/emmi-bot-lite/lib/prism/
    - assets/assets/emmi-bot-lite/lib/prism/components/
    - assets/assets/emmi-bot-lite/lib/prism/themes/
    - assets/assets/emmi-bot-lite/media/
    - assets/emmi_core-Copy(9)/
    - assets/emmi_core/
    - assets/emmi_core/assets/
    - assets/emmi_core/blocs/
    - assets/emmi_core/examples/
    - assets/emmi_core/examples/media/
    - assets/emmi_core/lang/
    - assets/emmi_core/media/
    - assets/emmi_core/toolbox/
    - assets/emmi_core/vendor/
    - assets/emmi_core/vendor/snippets/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

