// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo18sjfSXv6jfyAEytR301TbiQwjVJ7lQ',
    appId: '1:36391250694:web:e9c9a4e7ce76f5e8f98c87',
    messagingSenderId: '36391250694',
    projectId: 'qubiqai-db7a3',
    authDomain: 'qubiqai-db7a3.firebaseapp.com',
    storageBucket: 'qubiqai-db7a3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiSa2vCqy4two7KkS38fMS7x5NtvaRIpE',
    appId: '1:36391250694:android:3ac01d27327aeed6f98c87',
    messagingSenderId: '36391250694',
    projectId: 'qubiqai-db7a3',
    storageBucket: 'qubiqai-db7a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVnnPp3kiLRDnvbxAnN_GRuoIYxhzFwgk',
    appId: '1:36391250694:ios:eca43c1f911e7045f98c87',
    messagingSenderId: '36391250694',
    projectId: 'qubiqai-db7a3',
    storageBucket: 'qubiqai-db7a3.firebasestorage.app',
    iosBundleId: 'com.example.littleEmmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVnnPp3kiLRDnvbxAnN_GRuoIYxhzFwgk',
    appId: '1:36391250694:ios:eca43c1f911e7045f98c87',
    messagingSenderId: '36391250694',
    projectId: 'qubiqai-db7a3',
    storageBucket: 'qubiqai-db7a3.firebasestorage.app',
    iosBundleId: 'com.example.littleEmmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo18sjfSXv6jfyAEytR301TbiQwjVJ7lQ',
    appId: '1:36391250694:web:017d5d5e28791a26f98c87',
    messagingSenderId: '36391250694',
    projectId: 'qubiqai-db7a3',
    authDomain: 'qubiqai-db7a3.firebaseapp.com',
    storageBucket: 'qubiqai-db7a3.firebasestorage.app',
  );

}