import * as Blockly from 'blockly';

export const droneBlocks = [
  {
    type: 'takeoff',
    message0: 'Takeoff',
    previousStatement: null,
    nextStatement: null,
    colour: 120,
    tooltip: 'The drone takes off from the ground.',
    helpUrl: '',
  },
  {
    type: 'land',
    message0: 'Land',
    previousStatement: null,
    nextStatement: null,
    colour: 0,
    tooltip: 'The drone lands safely.',
    helpUrl: '',
  },
  {
    type: 'move_forward',
    message0: 'Move Forward %1 cm',
    args0: [
      {
        type: 'field_number',
        name: 'DISTANCE',
        value: 20,
        min: 1,
        max: 500,
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 230,
    tooltip: 'Moves the drone forward by the specified distance.',
    helpUrl: '',
  },
  {
    type: 'move_backward',
    message0: 'Move Backward %1 cm',
    args0: [
      {
        type: 'field_number',
        name: 'DISTANCE',
        value: 20,
        min: 1,
        max: 500,
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 230,
    tooltip: 'Moves the drone backward by the specified distance.',
    helpUrl: '',
  },
  {
    type: 'move_left',
    message0: 'Move Left %1 cm',
    args0: [
      {
        type: 'field_number',
        name: 'DISTANCE',
        value: 20,
        min: 1,
        max: 500,
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 230,
    tooltip: 'Moves the drone left by the specified distance.',
    helpUrl: '',
  },
  {
    type: 'move_right',
    message0: 'Move Right %1 cm',
    args0: [
      {
        type: 'field_number',
        name: 'DISTANCE',
        value: 20,
        min: 1,
        max: 500,
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 230,
    tooltip: 'Moves the drone right by the specified distance.',
    helpUrl: '',
  },
  {
    type: 'rotate_left',
    message0: 'Rotate Left %1 degrees',
    args0: [
      {
        type: 'field_number',
        name: 'DEGREES',
        value: 90,
        min: 1,
        max: 360,
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 290,
    tooltip: 'Rotates the drone counter-clockwise.',
    helpUrl: '',
  },
  {
    type: 'rotate_right',
    message0: 'Rotate Right %1 degrees',
    args0: [
      {
        type: 'field_number',
        name: 'DEGREES',
        value: 90,
        min: 1,
        max: 360,
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 290,
    tooltip: 'Rotates the drone clockwise.',
    helpUrl: '',
  },
  {
    type: 'set_speed',
    message0: 'Set Speed %1 %',
    args0: [
      {
        type: 'field_number',
        name: 'SPEED',
        value: 50,
        min: 1,
        max: 100,
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 160,
    tooltip: 'Sets the drone speed (1-100%).',
    helpUrl: '',
  },
  {
    type: 'set_altitude',
    message0: 'Set Altitude %1 cm',
    args0: [
      {
        type: 'field_number',
        name: 'ALTITUDE',
        value: 100,
        min: 20,
        max: 300,
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 160,
    tooltip: 'Sets the drone altitude.',
    helpUrl: '',
  },
  {
    type: 'delay',
    message0: 'Wait %1 seconds',
    args0: [
      {
        type: 'field_number',
        name: 'SECONDS',
        value: 1,
        min: 0.1,
        max: 10,
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 260,
    tooltip: 'Waits for a specified amount of time.',
    helpUrl: '',
  },
  {
    type: 'circle_left',
    message0: 'Circle Left Radius %1 cm Angle %2 °',
    args0: [
      { type: 'field_number', name: 'RADIUS', value: 50, min: 10, max: 500 },
      { type: 'field_number', name: 'ANGLE', value: 360, min: 1, max: 720 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 230,
    tooltip: 'Fly in a circle to the left.',
    helpUrl: '',
  },
  {
    type: 'circle_right',
    message0: 'Circle Right Radius %1 cm Angle %2 °',
    args0: [
      { type: 'field_number', name: 'RADIUS', value: 50, min: 10, max: 500 },
      { type: 'field_number', name: 'ANGLE', value: 360, min: 1, max: 720 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 230,
    tooltip: 'Fly in a circle to the right.',
    helpUrl: '',
  },
  {
    type: 'go_to',
    message0: 'Go to X %1 Y %2 Z %3 cm',
    args0: [
      { type: 'field_number', name: 'X', value: 0 },
      { type: 'field_number', name: 'Y', value: 0 },
      { type: 'field_number', name: 'Z', value: 100 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 230,
    tooltip: 'Move to absolute coordinates.',
    helpUrl: '',
  },
  {
    type: 'flip_forward',
    message0: 'Flip Forward',
    previousStatement: null,
    nextStatement: null,
    colour: 180,
    tooltip: 'Perform a forward flip.',
    helpUrl: '',
  },
  {
    type: 'flip_backward',
    message0: 'Flip Backward',
    previousStatement: null,
    nextStatement: null,
    colour: 180,
    tooltip: 'Perform a backward flip.',
    helpUrl: '',
  },
  {
    type: 'flip_left',
    message0: 'Flip Left',
    previousStatement: null,
    nextStatement: null,
    colour: 180,
    tooltip: 'Perform a left flip.',
    helpUrl: '',
  },
  {
    type: 'flip_right',
    message0: 'Flip Right',
    previousStatement: null,
    nextStatement: null,
    colour: 180,
    tooltip: 'Perform a right flip.',
    helpUrl: '',
  },
  {
    type: 'set_led_color',
    message0: 'Set LED Color %1',
    args0: [
      { type: 'field_colour', name: 'COLOR', colour: '#00ff00' }
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 200,
    tooltip: 'Sets the drone LED color.',
    helpUrl: '',
  },
  {
    type: 'spiral_up',
    message0: 'Spiral Up Radius %1 cm Height %2 cm',
    args0: [
      { type: 'field_number', name: 'RADIUS', value: 50, min: 10, max: 200 },
      { type: 'field_number', name: 'HEIGHT', value: 100, min: 20, max: 500 },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 180,
    tooltip: 'Fly upwards in a spiral pattern.',
    helpUrl: '',
  },
  {
    type: 'emergency_stop',
    message0: 'EMERGENCY STOP',
    previousStatement: null,
    nextStatement: null,
    colour: 0,
    tooltip: 'Instantly cut power to motors.',
    helpUrl: '',
  },
  {
    type: 'hover',
    message0: 'Hover for %1 seconds',
    args0: [
      { type: 'field_number', name: 'DURATION', value: 2, min: 0.1, max: 60 }
    ],
    previousStatement: null,
    nextStatement: null,
    colour: 260,
    tooltip: 'Stay at current position.',
    helpUrl: '',
  },
];

export const initDroneBlocks = () => {
  Blockly.defineBlocksWithJsonArray(droneBlocks);
};
